spring:
  application:
    name: l05_spring_jpa_emp
    profiles:
      include: dev_db

# DB 계정정보 따로 관리하는 방법 2
    logging:
      level:
        org.hibernate.orm.jdbc.bind: trace  # 쿼리 실행시 파라미터 보기

# DB 계정정보 따로 관리하는 방법 1
#  datasource:
#    username: ${mysql.user}
#    password: ${mysql.pw}
#    url: jdbc:mysql://localhost:3306/employees
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8181

