# sass?? tab? ????? ???
# YAML? ???? ????? ???? ? ???? "??? ??"
# ?? ?? ???? ??? ?? ?? ????, ???? ?? ??? ??? ?? ??? ??
# YAML? ?? ??:
# ????: YAML?? ????? ?? ?????. ????? 2? ?? 4? ???? ????? ???.
# ?-? ?: key: value ???? ???? ?????.
# ???: -? ???? ??? ??? ?????.
# ??: # ??? ???? ??? ??? ? ????.

spring:
  application:
    name: l04_spring_jpa

  datasource:
    username: ${mysql.user}
    password: ${mysql.pw}
    url: jdbc:mysql://localhost:3306/employees
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#    jap?? ???? ??? ?????.

server:
  port: 8181


# yaml ?? ??? ?? ??? ??
#   env.properties?? ??? ???? ??
#   main ???(L04SpringJapApplication)? ????? ??
#   @PropertySources(@PropertySource("classpath:/env.properties"))
#   gitignore? ?? ????.



